App/Controllers/LikeController.cs
using System;
using App.Models;
using App.Context;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace App.Controllers
{
    [Authorize]
    public class LikeController : Controller
    {
        private readonly QuestionsContext _db;
        private readonly ILogger<QuestionController> _logger;
        private readonly UserManager<User> _userManager;

        public LikeController(QuestionsContext db, ILogger<QuestionController> logger, UserManager<User> userManager) {
            _db = db;
            _logger = logger;
            _userManager = userManager;
        }

        /* Adds val to entity.Likes */
        [NonAction]
        public async Task<IActionResult> Change(Guid id, int val)
        {
            // TODO: Remove this
            if (Math.Abs(val) != 1) return BadRequest("Value can only be 1");

            var curUser = await _userManager.GetUserAsync(HttpContext.User);
            // If you already like this post
            if (_db.LikedPosts.Any(p => p.PostId == id && p.UserId == curUser.Id)) {
                _logger.Log(LogLevel.Critical, "You already liked/disliked this post");
                val = 0;
            }
            else
            {
                // Like and add to database
                curUser.LikedPosts.Add( new LikedPost() { PostId = id, UserId = curUser.Id });
            }

            // Find out that the like belongs to question or answer
            var question = await _db.Questions.FindAsync(id);
            // ANSWER
            if ( question == null )
            {
                var answer = await _db.Answers.FindAsync(id);
                if (answer == null) return NotFound("Non existing post !");
                answer.Likes += val;
                await _db.SaveChangesAsync();
                return RedirectToAction(
                    "Show", "Question", new { Id = answer.QuestionId });
            }
            // QUESTION
            else
            {
                question.Likes += val;
                await _db.SaveChangesAsync();
                return RedirectToAction("Show", "Question", new { Id = id });
            }
        }
        
        // GET: Like/Increment
        // Route: QuestionOrAnswerId, increment value
        public async Task<IActionResult> IncrementAsync(Guid id, int val) => await Change(id, 1);

        // GET: Like/Decrement
        // Route: QuestionOrAnswerId, increment value
        public async Task<IActionResult> DecrementAsync(Guid id, int val) => await Change(id, -1);
    }
}

App/Controllers/QuestionController.cs
using System;
using App.Models;
using App.Context;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace App.Controllers
{
    public class QuestionController : Controller
    {
        private readonly QuestionsContext _db;
        private readonly ILogger<QuestionController> _logger;
        private readonly UserManager<User> _userManager;

        public QuestionController(QuestionsContext db, ILogger<QuestionController> logger, UserManager<User> userManager) {
            _db = db;
            _logger = logger;
            _userManager = userManager;
        }

        // GET: Question/Show/Id
        [AllowAnonymous]
        public IActionResult Show(Guid id)
        {
            var question = _db.Questions.Where(p => p.Id == id).FirstOrDefault();

            if (question == null) return NotFound("Question not found !");

            return View(question);
        }

        // GET: Question/Create
        [Authorize]
        public IActionResult Create() => View();

        // POST: Question/Create
        // BODY: question
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CreateAsync(Question question)
        {
            if (!ModelState.IsValid) return View(question);

            var curUser = await _userManager.GetUserAsync(HttpContext.User);

            var curQuestion = new Question() {
                Id = Guid.NewGuid(),
                UserId = curUser.Id,
                Heading = question.Heading,
                Text = question.Text,
                CreationDate = DateTime.UtcNow
            };

            await _db.Questions.AddAsync(curQuestion);
            await _db.SaveChangesAsync();

            return RedirectToAction("Show", "Question", new { Id = curQuestion.Id });
        }


        // GET: Question/Answer
        [Authorize]
        public IActionResult Answer(Guid Id) => View();

        // POST: question/Answer/id
        // ROUTE: id
        // BODY: answer
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AnswerAsync(string id, Answer answer)
        {
            if (!ModelState.IsValid) return View(answer);

            var curUser = await _userManager.GetUserAsync(HttpContext.User);

            var curAnswer = new Answer()
            {
                Id = Guid.NewGuid(),
                CreationDate = DateTime.UtcNow,

                Heading = answer.Heading,
                Text = answer.Text,

                UserId = curUser.Id,
                QuestionId = Guid.Parse(id)
            };

            await _db.Answers.AddAsync(curAnswer);
            await _db.SaveChangesAsync();
            return RedirectToAction("Show", "Question", new { Id = curAnswer.QuestionId } );
        }
        // GET: Question/Comment
        [Authorize]
        public IActionResult Comment(string questionId) => View();

        // POST: Question/Comment/id
        // ROUTE: id
        // BODY: comment
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CommentAsync(string id, Comment comment)
        {
            if (!ModelState.IsValid) return View(comment);
            var curUser = await _userManager.GetUserAsync(HttpContext.User);

            var curComment = new Comment()
            {
                Id = Guid.NewGuid(),
                CreationDate = DateTime.UtcNow,
                Text = comment.Text,
                User = curUser,
                UserId = curUser.Id,
                QuestionId = Guid.Parse(id)
            };

            await _db.Comments.AddAsync(curComment);
            _db.SaveChanges();
            return RedirectToAction("Show", "Question", new { Id = id });
        }

        // GET: Question/CommentForAns/id
        // ROUTE: questionId
        [Authorize]
        public IActionResult CommentForAns(string questionId) => View();

        // POST: Question/CommentForAns/Id
        // ROUTE: id
        // BODY: comment
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CommentForAnsAsync(string id, Comment comment)
        {
            if (!ModelState.IsValid) return View(comment);
            var curUser = await _userManager.GetUserAsync(HttpContext.User);
            var answer = await _db.Answers.FindAsync(Guid.Parse(id));

            var curComment = new Comment()
            {
                Id = Guid.NewGuid(),
                CreationDate = DateTime.UtcNow,
                Text = comment.Text,
                User = curUser,
                UserId = curUser.Id,
                AnswerId = answer.Id
            };

            await _db.Comments.AddAsync(curComment);
            _db.SaveChanges();
            return RedirectToAction("Show", "Question", new { Id = answer.QuestionId } );
        }

        // GET: Question/Edit/id
        // ROUTE: id
        [Authorize]
        public async Task<IActionResult> EditAsync(Guid id)
        {
            var curUser = await _userManager.GetUserAsync(HttpContext.User);
            var question = await _db.Questions.FindAsync(id);
            if (question == null) return NotFound("Question not found !");

            if (!(await _userManager.IsInRoleAsync(curUser, "Admin")
                || await _userManager.IsInRoleAsync(curUser, "Moderator")) && 
                    question.UserId != curUser.Id)
                return Unauthorized("You are not the poster of this post !");

            return View(question);
        }

        // POST: Question/Edit/id
        // ROUTE: id
        // BODY: question
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditPostAsync(Guid id, Question question)
        {
            var curUser = await _userManager.GetUserAsync(HttpContext.User);
            question.Text += $"<small><sub>Edited by {curUser.UserName} on {DateTime.UtcNow}</sub></small>";

            var newQuestion = await _db.Questions.FindAsync(id);
            newQuestion.Heading = question.Heading;
            newQuestion.Text = question.Text;

            _db.SaveChanges();
            return RedirectToAction("Show", "Question", new { Id = id } );
        }

        // GET: Question/EditAnswer/id
        // ROUTE: id
        [Authorize]
        public async Task<IActionResult> EditAnswerAsync(Guid id)
        {
            var curUser = await _userManager.GetUserAsync(HttpContext.User);
            var answer = await _db.Answers.FindAsync(id);

            if (answer == null) return NotFound("Answer not found !");

            if (!(await _userManager.IsInRoleAsync(curUser, "Admin")
                || await _userManager.IsInRoleAsync(curUser, "Moderator")) && 
                    answer.UserId != curUser.Id)
                return Unauthorized("You are not the poster of this post !");

            return View(answer);
        }

        // POST: Question/EditAnswer/id
        // ROUTE: id
        [Authorize]
        [HttpPost("Question/EditAnswer/{id}")]
        public async Task<IActionResult> EditAnswerAsync(Guid id, Question question)
        {
            var newAnswer = await _db.Answers.FindAsync(id);
            if (newAnswer == null) return NotFound("Question not found !");

            var curUser = await _userManager.GetUserAsync(HttpContext.User);
            question.Text += $"<small><sub>Edited by {curUser.UserName} on {DateTime.UtcNow}</sub></small>";

            newAnswer.Heading = question.Heading;
            newAnswer.Text = question.Text;
            _db.SaveChanges();
            return RedirectToAction("Show", "Question", new { Id = newAnswer.QuestionId } );
        }

        // GET: Question/Delete/id
        // ROUTE: id
        [Authorize]
        public async Task<IActionResult> DeleteAsync(Guid id)
        {
            var question = await _db.Questions.FindAsync(id);
            if (question == null) return NotFound("Question not found !");

            // Remove dep
            question.Comments.Clear();
            question.Answers.Clear();
            question.Tags.Clear();


            _db.Remove(question);
            await _db.SaveChangesAsync();
            return RedirectToAction("ShowAll", "Question");
        }

        // GET: Question/DeleteAnswer/id
        // ROUTE: id
        [Authorize]
        public async Task<IActionResult> DeleteAnswerAsync(Guid id)
        {
            var answer = await _db.Answers.FindAsync(id);
            if (answer == null) return NotFound("Answer not found !");
            var question = await _db.Questions.FindAsync(answer.QuestionId);
            if (question == null) return NotFound("Question not found !");

            var curUser = await _userManager.GetUserAsync(HttpContext.User);
            if (!(await _userManager.IsInRoleAsync(answer.User, "Admin")
                || await _userManager.IsInRoleAsync(answer.User, "Moderator")
                || curUser.Id == answer.User.Id)) return Unauthorized();


            // Remove dep
            answer.Comments.Clear();

            // If this answer is a solution
            // We need to unmark the check
            if (answer.IsSolution)
            {
                question.IsSolved = false;
                answer.IsSolution = false;
                answer.User.Points--;
            }

            _db.Answers.Remove(answer);
            await _db.SaveChangesAsync();
            return RedirectToAction("Show", "Question", new { Id = answer.QuestionId } );
        }

        // GET: Question/MarkSolution
        // ROUTE: id
        [Authorize]
        public async Task<IActionResult> MarkSolutionAsync(string id)
        {
            var answer = await _db.Answers.FindAsync(Guid.Parse(id));
            if (answer == null) return NotFound("Answer not found !");

App/Views/Question/Answer.cshtml
@model App.Models.Answer
<body class="bg-light">
    <h1 class="text-center">Answer !</h1>
    @if (!ViewData.ModelState.IsValid)
    {
        <div asp-validation-summary="All" class="alert alert-danger"></div>
    }
    <div class="container">
        <form asp-action="Answer" asp-controller="Question" method="post">
            <textarea asp-for="Heading" class="form-control"> </textarea>
            <textarea asp-for="Text" class="form-control"></textarea>
            <div class="form-group">
                <button type="submit" class="btn btn-lg btn-success btn-block">Submit answer</button>
            </div>
        </form>
    </div>
</body>

App/Views/Question/Comment.cshtml
@model App.Models.Comment
<h1 class="text-center"> Comment ! </h1>
@if (!ViewData.ModelState.IsValid)
{
    <div asp-validation-summary="All" class="alert alert-danger"></div>
}
<div class="container">
    <form asp-action="Comment" asp-controller="Question" method="post">
        <textarea asp-for="Text" class="form-control"> </textarea>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Comment !</button>
        </div>
    </form>
</div>

App/Views/Question/CommentForAns.cshtml
@model App.Models.Comment
<h1 class="text-center"> Comment ! </h1>
@if (!ViewData.ModelState.IsValid)
{
    <div asp-validation-summary="All" class="alert alert-danger"></div>
}
<div class="container">
    <form asp-action="CommentForAns" asp-controller="Question" method="post">
        <textarea asp-for="Text" class="form-control"> </textarea>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Comment !</button>
        </div>
    </form>
</div>

App/Views/Question/Create.cshtml
@model App.Models.Question
<h4 class="card-title mt-3 text-center">Ask a question !</h4>

@if (!ViewData.ModelState.IsValid)
{
    <div asp-validation-summary="All" class="alert alert-danger"></div>
}

<form asp-action="Create" method="post">
    <div class="form-group input-group">
        <textarea asp-for="Heading" class = "form-control"> </textarea>
    </div>

    <div class="form-group input-group">
        <textarea asp-for="Text" class = "form-control"> </textarea>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block"> Ask !</button>
    </div>
</form>

App/Views/Question/Edit.cshtml
@model App.Models.Question
<h4 class="card-title mt-3 text-center">Edit you question !</h4>

<form asp-action="EditPost" asp-route-Id="@Model.Id" method="post">
    <div class="form-group input-group">
        <textarea asp-for="Heading" class = "form-control"> </textarea>
    </div>

    <div class="form-group input-group">
        <textarea asp-for="Text" class = "form-control"> </textarea>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-info btn-block"> Edit !</button>
    </div>
</form>

App/Views/Question/EditAnswer.cshtml
@model App.Models.Answer
<h4 class="card-title mt-3 text-center">Edit you Answer !</h4>

<form asp-action="EditAnswer" asp-route-Id="@Model.Id" method="post">
    <div class="form-group input-group">
        <textarea asp-for="Heading" class = "form-control"> </textarea>
    </div>

    <div class="form-group input-group">
        <textarea asp-for="Text" class = "form-control"> </textarea>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-info btn-block"> Edit !</button>
    </div>
</form>

App/Views/Question/Report.cshtml
@model App.Models.Post
<h1 class="text-center"> Report a post ! </h1>
@if (!ViewData.ModelState.IsValid)
{
    <div asp-validation-summary="All" class="alert alert-danger"></div>
}
<div class="container">
    <form asp-action="Report" asp-controller="Question" asp-route-Id="@Model.Id" method="post">
        <textarea asp-for="ReportText" class="form-control"> </textarea>
        <div class="form-group">
            <button type="submit" class="btn btn-danger btn-block">Report !</button>
        </div>
    </form>
</div>

App/Views/Question/Show.cshtml
@model App.Models.Question;

@using System.Text.RegularExpressions;
@using Microsoft.AspNetCore.Identity
@using App.Utils;
@inject UserManager<User> UserManager

<body class="bg-light">
    <!-- Reports for moderators -->
    @if (User.IsInRole("Moderator") && @Model.IsReported)
    {
            <div class="container my-3">
                <div class="btn-block alert alert-danger widt">
                    <h4 class="alert-heading">This question was reported !</h4>
                    <hr/>
                    @Html.Raw(@Model.ReportText)
                    <div class="d-flex justify-content-end">
                        <a class="btn btn-lg btn-success text-light" asp-action="SortOut" asp-route-Id="@Model.Id">Sort out</a>
                    </div>
                </div>
            </div>
    }
    <div class="container">
        @if (!ViewData.ModelState.IsValid)
        {
            <div asp-validation-summary="All" class="alert alert-danger"></div>
        }
        <div class="row">
            <div class="col-2">
                <div class="likecontrols">
                    <div class="btn-group-vertical">
                    <a asp-controller="Like" asp-action="Increment" asp-route-Id="@Model.Id" class="btn"><svg width="50" height="50" viewBox="0 0 36 36" fill="grey"><path d="M2 26h32L18 10 2 26Z"></path></svg></a>
                    <br/>
                    <div class="d-flex justify-content-center btn">
                        <span class="font-weight-bold">@Model.Likes</span>
                    </div>
                    <br/>
                    <a asp-controller="Like" asp-action="Decrement" asp-route-Id="@Model.Id" class="btn"><svg width="50" height="50" viewBox="0 0 36 36" fill="grey"><path d="M2 10h32L18 26 2 10Z"></path></svg></a>
                </div>

                </div>
            </div>
            <div class="col-10">
                <h1> @Html.Raw(@Model.Heading) </h1>
                <div class="row">
                    <div class="col">
                        <span class="text-truncate text-muted">Asked @Util.TimeAgo(@Model.CreationDate)</span>
                        @if ( User.Identity.IsAuthenticated )
                        {
                            <a asp-route-Id="@Model.Id" asp-controller="Question" asp-action="Report" class="btn btn-warning float-right m-1" data-toggle="tooltip" data-placement="top" title='@Regex.Replace(@Model.ReportText, @"<[^>]+>", "")'>
                                <span class="d-none d-md-block">

                                </span>
                                <i class="fas fa-flag"></i>
                            </a>
                        }

                        @if (Model.User.UserName == User.Identity.Name || User.IsInRole("Admin"))
                        {
                            <a asp-route-Id="@Model.Id" asp-controller="Question" asp-action="Edit" class="btn btn-info float-right m-1"><i class="fa fa-edit"></i></a>
                            <a asp-route-Id="@Model.Id" asp-controller="Question" asp-action="Delete" class="btn btn-danger float-right m-1"><i class="fas fa-trash-alt"></i></a>
                            <a asp-route-Id="@Model.Id" asp-controller="Tag" asp-action="AddTagToQuestion" class="btn btn-success float-right m-1"><i class="fas fa-tag"></i> </a>
                        }
                        else if (User.IsInRole("Moderator"))
                        {
                            <a asp-route-Id="@Model.Id" asp-controller="Question" asp-action="Edit" class="btn btn-info float-right m-1"><i class="fa fa-edit"></i></a>
                            <a asp-route-Id="@Model.Id" asp-controller="Tag" asp-action="AddTagToQuestion" class="btn btn-success float-right m-1"><i class="fas fa-tag"></i> </a>
                        }
                    </div>
                </div>
                <hr/>
                <div class="jumbotron p-3" style="word-wrap: break-word; max-width: 55rem;" >
                    @Html.Raw(@Model.Text)
                </div>

            <div class="row">
                <div class="col"> </div>
                <div class="col-4">
                    <span class="text-truncate text-muted">Asked @Util.TimeAgo(@Model.CreationDate)</span>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <small class="ml-4">Tags: </small>
                    @foreach (var tag in Model.Tags)
                    {
                        <span class="small">
                            <a asp-controller="Tag" asp-action="ShowByTag" asp-route-tagName="@tag.Name" class="btn border border-primary rounded bg-primary text-white mx-1 p-1"data-toggle="tooltip" data-placement="top" title='@Regex.Replace(@tag.Description ?? "", @"<[^>]+>", "")'>
                                @tag.Name
                            </a>
                        </span>
                    }
                </div>
                <div class="col-4">
                    <a asp-controller="Account" asp-action="ShowProfile" asp-route-Id="@Model.User.Id"> <img src="@Model.User.ProfilePicPath"; class="img-fit img-responsive img-rounded img-thumbnail" style="max-height: 55px; max-width: 55px;"> </a>
                    <a asp-controller="Account" asp-action="ShowProfile" asp-route-Id="@Model.User.Id">@Model.User.UserName</a>
                </div>
            </div>

            <div class="comments">
                <hr/>
                @foreach (var comment in Model.Comments) 
                {
                    <div class="my-3 p-3 bg-white rounded box-shadow border-bottom border-gray">
                        <div class="row">
                            <div class="col-8" style="word-wrap: break-word;">
                                @Html.Raw(@comment.Text)
                            </div>

                            <div class="col-sm-2">
                                <a asp-controller="Account" asp-action="ShowProfile" asp-route-Id="@Model.User.Id" class="text-primary">@comment.User.UserName</a>
                                <span class="d-inline-block text-truncate text-muted">@Util.TimeAgo(@comment.CreationDate)</span>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <a class="btn btn-primary btn-block" asp-action="Comment" asp-route-Id="@Model.Id">Comment</a>

            </div>
        </div>
    </div>

    <div class="m-5">
        <h1>
            @Model.Answers.Count()
            @if (@Model.Answers.Count() != 1) {
                <span> Answers </span>
            } else {
                <span> Answer </span>
            }
        </h1>
    </div>
    <hr/>
    <!-- Answers -->
    <div class="container">
        @foreach (var answer in Model.Answers)
        {
            <div class="row">
                <div class="col-2">
                    <div class="likecontrols">
                        <div class="btn-group-vertical">
                            <a asp-controller="Like" asp-action="Increment" asp-route-Id="@answer.Id" class="btn"><svg width="50" height="50" viewBox="0 0 36 36" fill="grey"><path d="M2 26h32L18 10 2 26Z"></path></svg></a>
                            <br/>
                            <div class="d-flex justify-content-center btn">
                                <span class="font-weight-bold">@answer.Likes</span>
                            </div>
                            <br/>
                            <a asp-controller="Like" asp-action="Decrement" asp-route-Id="@answer.Id" class="btn"><svg width="50" height="50" viewBox="0 0 36 36" fill="grey"><path d="M2 10h32L18 26 2 10Z"></path></svg></a>
                        </div>
                        <!-- TODO: REMOVE ISSOLVED CHECK FROM HERE TO THE CONTROLLER --> 
                        @if ((Model.User.UserName == User.Identity.Name || User.IsInRole("Moderator") || User.IsInRole("Admin")) && !Model.IsSolved)
                        {
                            <a class="btn" asp-action="MarkSolution" asp-route-Id="@answer.Id">
                                <svg class="checkmark" width="50" height="50" viewBox="0 0 36 36"><path d="m6 14 8 8L30 6v8L14 30l-8-8v-8Z"></path></svg>
                            </a>
                            <style>
                                .checkmark {
                                    fill: grey;
                                }
                            </style>
                        }
                        else if (Model.IsSolved && answer.IsSolution)
                        {
                            <a class="btn">
                                <svg class="checkmark" width="50" height="50" viewBox="0 0 36 36"><path d="m6 14 8 8L30 6v8L14 30l-8-8v-8Z"></path></svg>
                            </a>
                            <style>
                                .checkmark {
                                    fill: green;
                                }
                            </style>
                        }
                    </div>
                </div>
                <div class="col-10">
                    <h1 style="word-wrap: break-word"> @Html.Raw(@answer.Heading) </h1>

                    <div class="row">
                            <div class="col">
                            <span class="text-truncate text-muted">Answered @Util.TimeAgo(@answer.CreationDate)</span>
                                @if (User.IsInRole("Moderator") || answer.User.UserName == User.Identity.Name || User.IsInRole("Admin"))
                                {
                                    <a asp-route-Id="@answer.Id" asp-controller="Question" asp-action="EditAnswer" class="btn btn-info float-right ml-2">Edit</a>
                                    @if (answer.User.UserName == User.Identity.Name || User.IsInRole("Admin"))
                                    {
                                        <a asp-route-Id="@answer.Id" asp-controller="Question" asp-action="DeleteAnswer" class="btn btn-danger float-right">Delete</a>
                                    }
                                }
                            </div>
                    </div>

                    <hr/>
                    <div class="jumbotron p-3">
                        @Html.Raw(@answer.Text)
                    </div>
                    <div class="row">
                            <div class="col"></div>
                            <div class="col-4">
                                <small class="text-muted">Answered @Util.TimeAgo(@answer.CreationDate)</small>
                                <div class="text-muted small">
                                    <a asp-controller="Account" asp-action="ShowProfile" asp-route-Id="@answer.UserId"> <img src="@answer.User.ProfilePicPath"; class="img-fit img-responsive img-rounded img-thumbnail" style="max-height: 55px; max-width: 55px;"> </a>
                                    <a asp-controller="Account" asp-action="ShowProfile" asp-route-Id="@answer.UserId" class="ml-1">@answer.User.UserName</a>
                                </div>
                            </div>
                    </div>

                <div class="comments">
                    <hr/>
                    @foreach (var comment in answer.Comments) 
                    {
                        <div class="my-3 p-3 bg-white rounded box-shadow border-bottom border-gray">
                            <div class="row">
                                <div class="col-8" style="word-wrap: break-word;">
                                    @Html.Raw(@comment.Text)
                                </div>

                                <div class="col-sm-2">
                                    <a asp-controller="Account" asp-action="ShowProfile" asp-route-Id="@Model.User.Id" class="text-primary">@comment.User.UserName</a>
                                    <span class="d-inline-block text-truncate text-muted">@Util.TimeAgo(@comment.CreationDate)</span>
                                </div>
                            </div>
                        </div>
                    }
                    </div>
                        <a class="btn btn-primary btn-block" asp-action="CommentForAns" asp-route-Id="@answer.Id">Comment</a>
                    </div>
                </div>
        <hr/>
        }
    </div>

    <a class="btn btn-lg btn-success d-flex justify-content-center" asp-controller="Question" asp-action="Answer" asp-route-Id="@Model.Id"> Answer ! </a>
</body>

<!-- Normalize images -->
<style>
img {
    max-width: 100%;
    height: auto;
}
</style>